title: Evaluation in VR
description: How to Evaluate Object Selection and Manipulation in VR? Guidelines from 20 Years of Studies. Guidelines for evaluating object selection and manipulations, maintained by the HCI community.
url: "https://vrevaluation.github.io"
remote_theme: pmarsceill/just-the-docs

search:
  heading_level: 6

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
